# Generated by Django 4.2.1 on 2023-06-05 11:07

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.home.models.make_nanoid,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("heading", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        help_text="Image should be of dimention 1045x720.",
                        upload_to="home/image/HeroSection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
