# Generated by Django 4.2.1 on 2023-07-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('custom_plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroChildPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Image should be of dimention 1045x720.', upload_to='home/image/HeroSection')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
