# Generated by Django 4.2.1 on 2023-07-14 03:46

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('custom_plugins', '0002_herochildplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herochildplugin',
            name='image',
            field=filer.fields.image.FilerImageField(help_text='Image should be of dimention 1045x720.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
    ]
