# Generated by Django 4.2.1 on 2023-07-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('custom_plugins', '0003_alter_herochildplugin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('h31', models.CharField(max_length=50, verbose_name='Heading Text 1')),
                ('p1', models.TextField(verbose_name='Paragraph Text 1')),
                ('h32', models.CharField(max_length=50, verbose_name='Heading Text 2')),
                ('p2', models.TextField(verbose_name='Paragraph Text 2')),
                ('h33', models.CharField(max_length=50, verbose_name='Heading Text 3')),
                ('p3', models.TextField(verbose_name='Paragraph Text 3')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
